#' @title Generate (interactive) plots for multi-group comparisons of continuous estimates
#'
#' @description Plots the lower triangular visualization
#' based on a provided matrix
#'
#' @param estimates A \code{triviz_estimates} object generated by the package's suite
#' of \code{get_est} commands or a user-supplied object of equivalent structure (for
#' details, please see the vignette)
#' @param type Specifies how uncertainty estimates are derived (evaluated only when
#' \code{estimates} is a user-supplied object). Input must be one of
#' \code{"analytical"}, \code{"simulation"}, \code{"bootstrap"}, or \code{"bayesian"}.
#' @param variable Column name of the continuous predictor along which estimates will
#' be plotted
#' @param variable_label Label for the continuous predictor along which estimates will
#' be plotted
#' @param round_dec Number of decimal points for rounding of the x-axis
#' @param color_palette Character specifying the name of the color palette to be used.
#' Defaults to \code{"viridis"}.
#' @param one_tailed_test = (evaluated only when \code{estimates} is a user-supplied object)
#' @param p_val_threshold = (evaluated only when \code{estimates} is a user-supplied object)
#' @param p_val_type (evaluated only when \code{estimates} is a user-supplied object)
#' @param interactive A logical flag indicating whether the plotting function should
#' produce an interactive ShinyApp or a static ggplot2 object (the default)
#'
#' @export

plot_continuous_estimates <- function(estimates,
                                      type = c("analytical",
                                               "simulation",
                                               "bootstrap",
                                               "bayesian"),
                                      variable,
                                      variable_label = NA,
                                      round_dec = 2,
                                      color_palette = "viridis",
                                      one_tailed_test = FALSE,
                                      p_val_threshold = 0.05,
                                      p_val_type = "p-value",
                                      interactive = FALSE) {
  ## Warnings
  if (missing(estimates)) {
    stop("Please pass a suitable object to `estimates`.")
  }

  if (missing(variable)) {
    stop("variable has to be supplied.")
  }

  ## Inferred arguments
  if (inherits(estimates, "triviz_estimates")) {
    ## Overwrite function arguments
    type <- estimates$type
    p_val_threshold <- estimates$alpha
    p_val_type <- ifelse(estimates$type == "bayesian",
                         "Posterior \n probability",
                         "p-value")
    one_tailed_test <- !estimates$twotailed
  } else {
    ## Integrity checks for non-triviz objects)
    if (!(all(c("expected_values", "contrasts") %in% names(estimates)))) {
      stop("Please pass a suitable object to `estimates`. See the documentation for details.")
    }
    if (!(all(
      c("Group", "EV", "SE" , "p", "lower", "upper") %in% colnames(estimates$expected_values)
    ))) {
      stop("Please pass a suitable object to `estimates`. See the documentation for details.")
    }
    if (!(all(
      c("Group1", "Group2", "FD", "SE", "p", "lower", "upper") %in% colnames(estimates$contrasts)
    ))) {
      stop("Please pass a suitable object to `estimates`. See the documentation for details.")
    }
  }

  ## Processing estimation data
  if (!interactive) {
    plot_ci <-
      build_plot_continuous_estimates(
        ev = estimates$expected_values,
        variable = variable,
        type = type,
        variable_label = ifelse(!is.na(variable_label),
                                variable_label,
                                variable),
        contrasts = estimates$contrasts,
        y_min = min(estimates$expected_values$lower),
        y_max = max(estimates$expected_values$upper),
        x_min = min(estimates$expected_values[, variable]),
        x_max = max(estimates$expected_values[, variable]),
        round_dec = round_dec,
        color_palette = color_palette,
        one_tailed_test = one_tailed_test,
        p_val_threshold = p_val_threshold,
        p_val_type = p_val_type
      )
    print(plot_ci)
    return(plot_ci)
  }

  shiny::shinyOptions(
    ev = estimates$expected_values,
    variable = variable,
    type = type,
    variable_label = ifelse(!is.na(variable_label),
                            variable_label,
                            variable),
    contrasts = estimates$contrasts,
    y_min = min(estimates$expected_values$lower),
    y_max = max(estimates$expected_values$upper),
    x_min = min(estimates$expected_values[, variable]),
    x_max = max(estimates$expected_values[, variable]),
    round_dec = round_dec,
    color_palette = color_palette,
    one_tailed_test = one_tailed_test,
    p_val_threshold = p_val_threshold,
    p_val_type = p_val_type
  )

  # Look for shiny app directory
  appDir <-
    system.file("shiny", "shiny_linear_predictions", package = "triviz")
  if (appDir == "") {
    stop("Could not find shiny directory. Try re-installing `triviz`.",
         call. = FALSE)
  }

  shiny::runApp(appDir)
}
