#' @title Generate (interactive) plots for multi-group comparisons of point estimates
#'
#' @description Plots expected values and triangular visualizations of their pairwise
#' differences based on a \code{triviz} objects
#'
#' @param estimates A \code{triviz_estimates} object generated by the package's suite
#' of \code{get_est} commands or a user-supplied object of equivalent structure (for
#' details, please see the vignette)
#' @param type Specifies how uncertainty estimates are derived (evaluated only when
#' \code{estimates} is a user-supplied object). Input must be one of
#' \code{"analytical"}, \code{"simulation"}, \code{"bootstrap"}, or \code{"bayesian"}.
#' @param round_dec Number of decimal points for rounding of the x-axis
#' @param color_palette Character specifying the name of the color palette to be used.
#' Defaults to \code{"viridis"}.
#' @param p_bars Show p-values as bars, not as shadings.
#' @param one_tailed_test = (evaluated only when \code{estimates} is a user-supplied object)
#' @param p_val_threshold = (evaluated only when \code{estimates} is a user-supplied object)
#' @param p_val_type (evaluated only when \code{estimates} is a user-supplied object)
#' @param interactive A logical flag indicating whether the plotting function should
#' produce an interactive ShinyApp or a static ggplot2 object (the default)
#' @param caption_exp A custom caption for the left-hand side of the plot.
#' @param caption_stat A custom caption for the right-hand side of the plot.
#' @param add_vline Optional: A numerical value for a red vertical line in the
#' left-hand side of the plot.
#' @param title Optional: A main title for the plot.
#' @param xlim Optional: A range of values for the horizontal axis of the left-hand side
#' of the plot.
#' @param show_lower_triangular_title Optional: Show lower triangular column titles
#' instead of arrows.
#'
#' @export

plot_point_estimates <- function(estimates,
                                 type = c("analytical",
                                          "simulation",
                                          "bootstrap",
                                          "bayesian"),
                                 round_dec = 2,
                                 color_palette = "viridis",
                                 p_bars = FALSE,
                                 one_tailed_test = FALSE,
                                 p_val_threshold = 0.05,
                                 p_val_type = "p-value",
                                 interactive = FALSE,
                                 caption_exp = "Expected values",
                                 caption_stat = "Statistical Significance of\nPairwise Differences",
                                 add_vline = NULL,
                                 title = NULL,
                                 xlim = NULL,
                                 show_lower_triangular_title = FALSE) {
  ## Warnings
  if (missing(estimates)) {
    stop("Please pass a triviz_estimates object to `estimates`.")
  }

  ## Inferred arguments
  if (inherits(estimates, "triviz_estimates")) {
    ## Overwrite function arguments
    type <- estimates$type
    p_val_threshold <- estimates$alpha
    p_val_type <- ifelse(estimates$type == "bayesian",
                         "Posterior \n probability",
                         "p-value")
    one_tailed_test <- !estimates$twotailed
  } else {
    ## Integrity checks for non-triviz objects)
    if (!(all(c("expected_values", "contrasts") %in% names(estimates)))) {
      stop(
        paste(
          "Analytical list must include the members",
          "'expected_values' and 'contrasts'.",
          sep = " "
        )
      )
    }
    if (!(all(
      c("EV", "SE" , "p", "lower", "upper") %in% colnames(estimates$expected_values)
    ))) {
      stop(
        paste(
          "Expected values must include the columns",
          "'EV', 'SE', 'p', 'lower' and 'upper'.",
          sep = " "
        )
      )
    }
    if (!(all(
      c("FD", "SE", "p", "lower", "upper") %in% colnames(estimates$contrasts)
    ))) {
      stop(
        paste(
          "Contrasts must include the columns",
          "'FD', 'SE', 'p', 'lower' and 'upper'.",
          sep = " "
        )
      )
    }
  }

  span <-
    abs(max(estimates$expected_values$lower) - min(estimates$expected_values$lower))

  if (is.null(xlim)) {
    xlim <- c(min(estimates$expected_values$lower) - 0.1 * span,
              max(estimates$expected_values$upper) + 0.1 * span)
  }

  if (!interactive) {
    plot_ci <-
      build_plot_point_estimates(
        ev = estimates$expected_values,
        contrasts = estimates$contrasts,
        type = type,
        groups = rev(seq(
          1, nrow(estimates$expected_values), 1
        )),
        x_min = xlim[1],
        x_max = xlim[2],
        round_dec = round_dec,
        color_palette = color_palette,
        p_val_threshold = p_val_threshold,
        p_val_type = p_val_type,
        p_bars = p_bars,
        caption_exp = caption_exp,
        caption_stat = caption_stat,
        add_vline = add_vline,
        title = title,
        one_tailed_test = one_tailed_test,
        show_lower_triangular_title = show_lower_triangular_title
      )
    return(plot_ci)
  } else {
    if (show_lower_triangular_title) {
      stop("Lower triangular titles (show_lower_triangular_title) are not supported for interactive plots.")
    }

    if (type == "analytical") {
      shiny::shinyOptions(
        ev = estimates$expected_values,
        contrasts = estimates$contrasts,
        type = type,
        groups = rev(seq(
          1, nrow(estimates$expected_values), 1
        )),
        round_dec = round_dec,
        x_min = xlim[1],
        x_max = xlim[2],
        color_palette = color_palette,
        p_val_threshold = p_val_threshold,
        p_val_type = p_val_type,
        p_bars = p_bars,
        caption_exp = caption_exp,
        caption_stat = caption_stat,
        add_vline = add_vline,
        title = title,
        one_tailed_test = one_tailed_test
      )
    } else {
      shiny::shinyOptions(
        ev = estimates$expected_values,
        contrasts = estimates$contrasts,
        type = type,
        ev_draws = estimates$expected_values_draws,
        contrasts_draws = estimates$contrasts_draws,
        groups = rev(seq(
          1, nrow(estimates$expected_values), 1
        )),
        round_dec = round_dec,
        x_min = xlim[1],
        x_max = xlim[2],
        color_palette = color_palette,
        p_val_threshold = p_val_threshold,
        p_val_type = p_val_type,
        p_bars = p_bars,
        caption_exp = caption_exp,
        caption_stat = caption_stat,
        add_vline = add_vline,
        title = title,
        one_tailed_test = one_tailed_test
      )
    }

    # Look for shiny app directory
    appDir <-
      system.file("shiny", "shiny_point_estimate", package = "triviz")
    if (appDir == "") {
      stop("Could not find shiny directory. Try re-installing `triviz`.",
           call. = FALSE)
    }

    shiny::runApp(appDir)
  }
}
